<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{5d841a3c-4032-4429-ae88-cfe024ef2812}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[POU_readSupvData();
POU_writeReactorToSupvData();

	
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="72" Count="0" />
      <LineId Id="80" Count="0" />
      <LineId Id="67" Count="0" />
      <LineId Id="75" Count="0" />
      <LineId Id="31" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>